# Site settings
author: Heather Moreira
title: Learning to Code in 2020
header-img: img/home-bg.png
email: moreiraheather@gmail.com
copyright_name: Heather Moreira
description: > # this means to ignore newlines until "baseurl:"
  Blogging for Flatiron's Software Engineering Online program 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HMoreira2020

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
